### ISSUE TITLE
ALS landing and taxi lights disappear depending on throttle amount

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#174]
When using ALS the landing lights (and also taxi lights) disappear when the throttle is above a certain amount. wlbragg also confirmed that he can reproduce this bug. This problem has not been present all along in our development so we may be able to trace back when it was introduced.

**Comment by onox** [comment]
I can't reproduce it with the throttle, but I am able to make the lights turn off by turning *on* the alternator.

**Comment by gilbertohasnofb** [comment]
@onox using ALS as well? I tried to reproduce your alternator bug but I can't make it happen on my system. Here is what I tried:

bat OFF, alt OFF, engine OFF: no landing lights as expected
bat ON, alt OFF, engine OFF: landing lights on as expected
bat OFF, alt ON, engine OFF: no landing lights as expected (since the engine is not running)
bat OFF, alt OFF, engine ON: no landing lights as expected
bat ON, alt OFF, engine ON: landing lights on as expected
bat OFF, alt ON, engine ON: landing lights on as expected

As for the bug I reported on this issue, the problem happens when the throttle is set above around 750 RPM. For instance, when I autostart, the landing lights go off immediately, but pulling the throttle just a bit makes it appear again. Same for taxi lights.

**Comment by gilbertohasnofb** [comment]
@wlbragg can you confirm you can reproduce this bug? Do you also see the problem when the RPM is around 750?

**Comment by onox** [comment]
@gilbertohasnofb You're right, now it's the throttle :smile: And I know what's causing it. Check the value of `/systems/electrical/outputs/landing-lights`. I have defined the range for the ALS lights to be greater than 20 V and less than 28 V.

Normally the value floats around 24 V, but sometimes, when I turn on the alternator for example, it jumps to 28 V without floating.

**Comment by gilbertohasnofb** [comment]
Just one more info: it's actually related to the RPM, not the throttle itself. E.g.: After autostarting the plane, the RPM is slightly above 750 and there are no landing lights. If I pull the throttle a bit the lights appear, but also if I leave the throttle on the autostart position (25% if I am not mistaken) and then pull the mixture a bit (thus reducing the RPM) the lights also come back to life. 

Cool that you find the culprit :+1:

**Comment by wlbragg** [comment]
So is it the upper limit that is causing the trouble or lower or both?
If the upper, why have an upper boundary it either has juice or it doesn't?

**Comment by Juanvvc** [comment]
The calculation of the available volts for the landing lights (/systems/electrical/outputs/landing-lights) is in electrical.nas, and it does depend on the RPM when the alternator is ON. In fact, there is a threshold exactly at 800RPM when the alternator is ON. I'll check the function to calculate the available volts in AlternatorClass tonight, maybe there is a bug there.

**Comment by Juanvvc** [comment]
Fixed. The upper limit has been raised to 31.5, as suggested in the previous link

**Comment by onox** [comment]
I'm okay with raising the limit, but it doesn't fix the problem that once you turn on the alternator of the master switch, that the voltages jump straight to 28 Volt. Shouldn't the voltage float a bit, like is happening when the alternator is turned off?

**Comment by wlbragg** [comment]
"Determine why the voltage sometimes stick to 28 V. Is it an upper bound"
I just re-read this and if this isn't by design, we do need to look at it and see why. Typically if you turn on an alternator you would see a bit of a jump in voltage. I know on a typical 12v car system the atl produces about 14v.

**Comment by gilbertohasnofb** [comment]
Guys, I believe this issue has been fixed, right? Right now I have both landing and taxi lights in ALS regardless of my RPM.

**Comment by onox** [comment]
The ALS lights are ok now, but I/we haven't checked yet why the voltage sticks to 28.0000000000000000 volts once you turn on the alternator :stuck_out_tongue_winking_eye:

**Comment by gilbertohasnofb** [comment]
> but I/we haven't checked yet why the voltage sticks to 28.0000000000000000 volts once you turn on the alternator

Should we maybe open an issue for that so this doesn't get lost/forgotten?

**Comment by onox** [comment]
Sure.

**Comment by gilbertohasnofb** [comment]
Do you think you could do it yourself? Sorry but I have no clue about the electrical system :disappointed:
