### ISSUE TITLE
spinner should rotate

### ISSUE THREAD

**Issue by tigert** [Juanvvc/c172p-detailed#183]
I guess CTL is the only livery with textured spinner (since the paint is so worn) - I noticed it doesnt spin with the propeller.

To make it work, one also needs the blurred "highspeed" textured spinner to match the propellers' equivalent.

**Comment by wlbragg** [comment]
I added the existing spinner. Even thought it works and looks cool, it needs a new texture. The existing texture has hard-coded shading and light reflection. It needs to have those concepts removed, but leave enough imperfections in the paint job to allow for visual cue as to its spinning. I'm not sure we need a blurred version?

**Comment by gilbertohasnofb** [comment]
I will rework this textures in the next days once I am back home. 

> one also needs the blurred "highspeed" textured spinner to match the propellers' equivalent.

If this is possible, I can prepare the texture, but someone else would need to help programming the transition from one texture to another according to the RPM (is this even possible?)

**Comment by wlbragg** [comment]
I guess you would use a different (duplicated) spinner with the high speed texture applied to it. The rotate animation is already in the Models/*.xml file. That is where I put the one and only existing spinner. Like I said, it looked OK to me other than the texture. We can see what it looks like with a new texture and then decide.

**Comment by gilbertohasnofb** [comment]
> We can see what it looks like with a new texture and then decide.

Sounds good, I will prepare it ASAP and then we decide.

**Comment by gilbertohasnofb** [comment]
I think this should be closed, right? Spinners are now rotating and there is no hard coded shadow. What you all think?

**Comment by wlbragg** [comment]
I was referring to the darker shading on the bottom of the spinner.
![spn](https://cloud.githubusercontent.com/assets/11069680/7740309/ff370d24-ff34-11e4-8331-087cb8002ecd.jpg)

**Comment by wlbragg** [comment]
Sorry, didn't mean to close it. Notice the shadow on the bottom, that is what I was talking about.

**Comment by gilbertohasnofb** [comment]
Done. Sorry, all other liveries were already fixed but I missed the D-EEQA.

**Comment by wlbragg** [comment]
Your not going to like me very much but this is still not finished, is it?
![spin](https://cloud.githubusercontent.com/assets/11069680/7765325/5a92349e-0022-11e5-98ee-d18d9847edf3.jpg)
All the livery's still have shading below.
Also, if you indeed haven't finished this and are going to remove the shading, could you add some kind of imperfections, small scratches or paint chip, or even dirt marks so we can still see it spin.

**Comment by gilbertohasnofb** [comment]
> Note it is turned to the vertical instead of horizontal.

I don't think this is due to the texture. Please have a look on all the fuselage.png files located inside the Livery folder (and its subfolders), all the spinners on them are made out of solid colours! I double checked them already and I am sure this is not due to texturing. Can you confirm this, please?

> could you add some kind of imperfections, small scratches or paint chip, or even dirt marks so we can still see it spin.

Yes, I can do that. My initial concept was that some liveries should look older than others, so for instance OH-CTL is very scratched, PT-IAO is quite dirty, 4X-CHV, ZS-MDF and N35799 are almost completely clean. I will add some scratches and imperfections to them according to these ideas, if that's fine with you.

**Comment by wlbragg** [comment]
"I will add some scratches and imperfections to them according to these ideas"
Yes, fine with me.

I didn't look at the textures.

"Can you confirm this, please?"
Yes, your right

I thought maybe it was coming from
Aircraft/c172p-detailed/Models/Liveries/fuselage-normal.png
But I don't see it in there.

Wow, now I am stumped. I guess we need an expert....

It's not that big a deal, I just noticed it and it technically isn't right.

**Comment by wlbragg** [comment]
I suppose it could be specular lighting that is applied and stays where it is applied when it is applied? I know nothing about the light effects.

**Comment by wkitty42** [comment]
when i looked earlier, what i was seeing was shadows from the light... when i changed the sun angle (time of day) the shadow changed, too... AFAICT, the spinners spin as desired on all of the craft... i turned the magnetos off and set each livery while in heli view zoomed in on the front of the craft... when the livery loaded, i hit the starter button to turn the prop... looked quite ok to me...

**Comment by gilbertohasnofb** [comment]
Yes, this is not being caused by the textures nor by the normal map (I also checked it). I don't think it's so much of a big deal, but let's leave this opened in case someone has a brilliant idea :)

**Comment by wlbragg** [comment]
"i hit the starter button to turn the prop... looked quite ok to me..."
But you do see the subtle change in shade between the top half and the bottom half, right?
And when you spin the prop the transition line rotates so the shade below rotates around to the top and then back down the other side. A shadow or shade shouldn't do this.
Unless this is paint fading, we could chalk it up to that:)

**Comment by gilbertohasnofb** [comment]
> But you do see the subtle change in shade between the top half and the bottom half, right?

Actually, I don't. I just tested it with the ZS-MDF livery and I don't see the same as your screen shot above. Have a look on this sequence of images:

http://s22.postimg.org/4spoq1hap/fgfs_screen_003.png
http://s22.postimg.org/vhm11up5d/fgfs_screen_004.png
http://s22.postimg.org/vhm11up5d/fgfs_screen_004.png
http://s24.postimg.org/c0yxfhuz9/fgfs_screen_006.png
http://s16.postimg.org/vd5sjbr79/fgfs_screen_007.png
http://s11.postimg.org/58anhjqsj/fgfs_screen_008.png

**Comment by wkitty42** [comment]
@wlbragg i don't know what you are seeing... what i see looks like what @gilbertohasnofb posted in his images... i can't take image snapshots that fast though ;)

**Comment by gilbertohasnofb** [comment]
> i can't take image snapshots that fast though ;) 

Ha! You simply prepare the plane for starting, and instead of holding down the s key to start the engine, you just hit the key very quickly. This way, the propeller turns just a little bit and then stop :wink:

**Comment by wlbragg** [comment]
Weird, yeah your not seeing what I am. I guess this is a done deal. It really isn't a big deal at any rate. Thanks for looking into it.

**Comment by gilbertohasnofb** [comment]
No problems, wlbragg. I will close the issue now, but please feel free to reopen it if you have any suspicion of what may be causing the problem you are seeing, ok?

**Comment by gilbertohasnofb** [comment]
@wlbragg wrote:

> could you add some kind of imperfections, small scratches or paint chip, or even dirt marks so we can still see it spin.

Just did that for all high resolution liveries as well as for the default D-EEQA livery. The question is: are you still using a different copy of fuselage.png for the demage model or did you manage to link it to the livery file being used? I ask that because concerning the D-EEQA livery, I only replaced the fuselage.png file located in the Model folder, nothing else.

**Comment by wkitty42** [comment]
@gilbertohasnofb "I just added some simple dirt in the spinner of all high resolution liveries as well as for the default D-EEQA livery."
is that really OK? it seems to me, without any real life experience in this aspect, that dirt just cannot accumulate on the spinner... maybe i'm missing something but it just seems that something that is in motion ""all the time"" just cannot build up any dirt coating... granted, i've not yet updated to this commit to see what you are speaking of... that will happen in a little bit when i grab the latest ;)

**Comment by gilbertohasnofb** [comment]
@wkitty42 when I wrote dirt, I rather mean irregularities, not literally dirt. I just didn't want the texture to look completely uniform. Have a look on them and if you think that's too much, then I can revert back to the original solid colour spinners, so let me know what you think!
