### ISSUE TITLE
On starter who is messing with the throttle?

### ISSUE THREAD

**Issue by geoffmcl** [Juanvvc/c172p-detailed#376]
Hey, who is MESSING with the throttle when I engage the starter? Or have I got something wrong?

The previous behaviour was the c172p would start and idle even though the throttle level is pull full out... 0%

Now 'someone' is setting the throttle to 10-20% just because I engage the starter... I do not think this should happen???

The previous, old correct behaviour is still there... That is pulling the throttle level full out, to 0%, does **NOT** stop the engine. It will continue to idle... that is even when /controls/engines/engine is 0.

As normal in this type of aircraft you can not stop the engine using the throttle, instead it is done by pulling out the mixture... it is usually only necessary to lean it down to less than 80% rich, and the engine will starve and stop...

Will search for where and why this connection between an electric engagement of the start and the mechanical throttle, but maybe someone could give at least some discussion pointers...

**Comment by dany93** [comment]
(I haven't written this code. I guess you are in autostart, where everything is pre-set for beginners and lazy ones :smiley: )

Many aircraft engines need a bit of throttle to start. Of course, it can be back to zero later.
This is the case for this one (1/8 inch for the 1982, 160 hp version)
[c172p 1982 POH](http://www.aerodynamicaviation.com/documents/cessna-172p-1982-poh.pdf)
pdf page 62/357, or 4-12
 I also see 1/4 inch for a 180 hp version.

**Comment by Juanvvc** [comment]
I also guess you are talking about autostart. When you press autostart, many things are configured automatically, including the throttle.

Starting an engine is more an art than a science. Every single engine is different. For example, on my (real) c172, you had to push slowly the throttle while cracking. All the checklists out there say you must set the throttle about 15% before starting the engine, and I can confirm my c172p didn't start with throttle at 0%. This is the behaviour simulated in this aircraft.

**Comment by geoffmcl** [comment]
@Juanvvc I am **NOT** talking about an autostart... I am just talking about pushing the starter button...

If I have left the throttle at 0% then that is where it should stay... engaging the starter should have no influence on what the throttle lever is at... and it should not change that lever...

AFAIK the start criteria was that the rpm reached a certain minimum... if this was reached, the engine would start...

I absolutely AGREE starting an engine is an ART ;=)) Getting the right conditions for a start can be tricky, especially if it is going to be swung by hand. Had to do this in a 182 one morning when the battery had run down... Others require two primer pumps, but **not** 3... Sounds like your 172 needs to feel hand pressure on the throttle lever, which is exactly where is should be... each engine quite unique...

So if you want to change the simulation criteria to if the level is at 0%, then limit the cranking speed to below the minimum, and thus stop the engine starting... That would be a good move...

But do not use the click action of engaging the manual starter as a reason for altering the throttle level...

**Comment by geoffmcl** [comment]
Specifically with `autostart' there is another BUG related to engaging the start 's'...

Autostart sets STD pressure, which is not particularly a problem...

Then I will adjust the altimeter to zero, thus setting my local QNH...

Now when I press `s`, then STD pressure is re-set...

Again I would ask why is this physically engaging a mechanical starter is altering other things?

It does **not** do this in c172p 3.4--...

So selecting the menu item `autstart` can most certainly set up a few things... one thing I think it forgets is to set the brake... whether it should set STD or not would be a question... it did in the old so why not the new... both set the throttle to 20%... that is all fine, and correct...

But pressing 's' should not, and did not previously reset QNH...

This could be posted as a separate bug, but since it seems related to actions added to a 's', then this is also the right place ;=))

**Comment by wkitty42** [comment]
@geoffmcl on the setting of the parking brake - this is dependent on where you start in the sim... if you start in a parking space and follow the checklists, then everything works out properly... if you use the autostart in a parking space, it also works out and you are ready to taxi out to the runway... if, on the other hand, you start on the runway, the brake has already been released before you got there so it shouldn't be set when you start from there...

that's the gist of what i got from others when i brought this up some issues back... starting on the runway is not realistic, apparently... i do, however, agree that there should be some mechanism of detecting if one is starting in a parking place or at the end of the runway and the brake set as appropriate... not being a real pilot, i prefer to either start on the runway or roll out onto it, get lined up and stopped with the brake set... then i run the throttle full up and release the brake when max thrust is reached... i do this with *all* craft i fly (except the UFO and the bluebird hovercraft)... maybe this is akin to launching a craft from the deck of an aircraft carrier? i dunno but it is how i've always done it since way way back when microsoft's flight simulator first came out and i was flying with it on an IBM PCjr back in the '80s :wink:

**Comment by onox** [comment]
> Now 'someone' is setting the throttle to 10-20% just because I engage the starter... I do not think this should happen???

Cannot reproduce.

> Now when I press s, then STD pressure is re-set...

Cannot reproduce.

**Comment by dany93** [comment]
I can reproduce it.
version: from juanvvc:master, 05 jul 2015
![capture du 2015-07-06 10 07 35](https://cloud.githubusercontent.com/assets/11994061/8518070/005e0e94-23c7-11e5-85a2-ef925bf97c49.png)
- KSFO (QNH a bit different from 0 at sim opening, will be 0 after "s", which I call the preset)
- Opening the sim from FGRun,
- I press "s" ==> QNH = 0 and throtlle = 20%. Engine starts.
- I set a QNH (different from the previous one, i.e. different from 0) and throttle > 20%.
- I stop  the engine *by any mean* (magnetos, mixture, throttle too early)
- "s" again ==> the QNH is back to the preset value (0 for me at KSFO), and throttle back to 20%.

Seen with 160 hp and 180hp.

- Having to restart the engine later can happen. Resetting the QNH may be too much. And, if this is more simple for you (no conditions), not having the QNH set at all is not a big issue for beginners.
- For the throttle at 20%, it does not bother me in the context of autostart, where a mere "s" works very well each time.

**Comment by onox** [comment]
I can see what's going on here. @geoffmcl must have `Complex start up procedures" turned off!` If you have that check box disabled, then pressing "s" will set the QNH and throttle. So @geoffmcl got what he wanted :stuck_out_tongue_winking_eye: 

Why do we have that checkbox anyway? All you need to do is click "Autostart" in the menu, and then press "s" if you're lazy (I am :laughing:).

Why do we have that checkbox anyway? We could remove it and then make "Autostart" a full autostart instead of a semi-autostart.

**Comment by geoffmcl** [comment]
@dany93 thanks for reproducing it ;=))

I posted a page - http://geoffair.org/fg/c172d-376.htm - to expand on what I am talking about... and add some pictures...

 * Agree 's' resetting QNH is **too** much!
 * 's' setting throttle to 20% is wrong. The first action of the pilot is to pull it to zero, that is to idle, so 's' should either start the engine or not depending on multiple conditions, but it should not change the throttle setting.

Maybe my 172 likes to turn over a few times before I manually apply some throttle... I would not like the level to jump in my hand and suddenly land at 20% just because I turned the key...

@onox, so what is this 'Complex start up procedures'? Yes it is on the default you set it too... off?

Now it seems I need that ON to get the previous 's' behaviour. Ok, then default it to ON!

But then am quite confused!

On unchecking this 'Complex', you would expect the opposite, like 'simple'...

Then what is a 'simple' 's' doing with QNH? Throttle? That seems 'complicated'!?!?

And **NO** I do not think we should have a full autostart that includes the 's'. 

It is sufficient that they see 'Hold down "s" to start the engine' tooltip...

And all of this is the **DEFAULT** behaviour of the c172p you are replacing.

For sure new 'options' can be added, but should probably not do a bunch of strange things in their default mode...

But still wonder what is the real use of this new 'Complex start up procedures' on/off. Where is the documentation on what it is supposed to control, change? Maybe it could be removed...

Off topic a little. I wrote a `blog` mainly about c172p-detailed - http://geoffair.org/fg/fgc172p.htm - with some contrast pictures, and some mp pictures, with the `sad` broken winged 3.4 when viewed in 3.5+ you may be interested in...

**Comment by onox** [comment]
This is what is happening:

```javascript
155 setlistener("/controls/switches/starter", func {
156     if (!getprop("/fdm/jsbsim/complex"))
157         autostart(0);
```

As you can see, if you press "s" then it will perform an autostart (basically clicking on "Autostart" in the menu for you) before it actually starts the engine.

1. I think we should set the default of "Complex start up procedures" to enabled.

2. Perhaps we should just remove the whole check box.

**Comment by onox** [comment]
> some mp pictures, with the sad broken winged 3.4 when viewed in 3.5+ you may be interested in...

I'm not interested in because it has already been fixed in https://github.com/Juanvvc/c172p-detailed/commit/e3ad3555fe247d12d252635f1cb80e918e7a7703.

**Comment by dany93** [comment]
@onox 
- Apart from the QNH auto-setting, I think it is very well like this. Press "s" (even without "Menu > Cessna 172p > Autostart") that's all, it works perfectly.
- I do not see the use of the "Menu > Cessna 172p > Autostart". Pressing "s" does the autostart rightly and perfectly. Historical remaining?
- "Complex start up procedures" disabled by default (like now) is the best IMO.  Beginners are welcome and happy. Later, everyone can check  "Complex start up procedures" and have it for the next time(s).

@geoffmcl 
>But still wonder what is the real use of this new 'Complex start up procedures' on/off

Did you try by checking it? Check it, quit the sim, re-start the sim. Easy to see how it works. And why it is called "Complex".

**Comment by Juanvvc** [comment]
> But still wonder what is the real use of this new 'Complex start up procedures' on/off. Where is the documentation on what it is supposed to control, change? Maybe it could be removed...

In the beginning, the project had two main goals: detailed textures and a realistic start-up process. This is called "complex start up procedures". Probably, "real" is more accurate than "complex". You don't need any specialized documentation about these procedures: to start the engine, you must follow accurately the checklists. This includes master, magnetos, primer, throttle... and, after the ignition, alternator, avionic master, avionics... Lots of things the old c172p model did not require. Since the start-up procedure is long, two automatic modes were implemented for the beginners: the fully-automated mode (autostart) and the semi-automatic mode (press 's') I agree there could be some confusion with these two automatic modes.

We can discuss if the automatic modes must set altimeter to QNH or QNE. The developers decided to set the QNH in the automatic modes, and I think it was a good decision: a beginner won't set the QNH during his first flights! When you get more experience, you are expected to turn complex procedures "on" and no one should mess with your settings :)

In any case, it seems you used to set the altimeter to QFE before starting the engine. Setting the altimeter and the other instruments is expected to be done during the taxi, when the engine is already started. Don't complain if we try to educate you to follow the checklists correctly!

Don't smoke on an aircraft! Seriously, don't. Smoking is prohibited since long ago, and the "No smoking" placard is mandatory at least according to the European regulations. It is in the manual!

**Comment by Juanvvc** [comment]
>  i prefer to either start on the runway or roll out onto it, get lined up and stopped with the brake set... then i run the throttle full up and release the brake when max thrust is reached...

This is the recommended procedure for short fields, along with one step of flaps. In long fields (longer than half a mile/one kilometer), using the brakes is not necessary and flaps should be UP. I prefer NOT using brakes in long runways to not wear them up. You may need these brakes in the very near future!

**Comment by dany93** [comment]
@Juanvvc wrote
 >two automatic modes were implemented for the beginners: the fully-automated mode (autostart) and the semi-automatic mode (press 's') I agree there could be some confusion with these two automatic modes.

All the more that you still have to *Hold on "s" to start the engine* with the Autostart...

**Comment by onox** [comment]
> fully-automated mode (autostart) and the semi-automatic mode (press 's')

That's not really how it works. See https://github.com/Juanvvc/c172p-detailed/issues/376#issuecomment-118801108

- "Autostart" is semi-automatic, it turns on the battery, sets the throttle, etc.

- "s" optionally does the semi-autostart and then after that always tries to start the engine (make the prop spin). If you have "Complex" set to OFF, then "s" becomes full autostart. If you have set "Complex" to ON, then "s" does:

    - Start the engine if you have clicked "Autostart" before it (or did everything manually)

    - Says "Use the primer!" if you have not clicked "Autostart" and haven't done anything manually

So a user has 3 choices:

1. Start manually

2. Start almost automatic (click "Autostart", then hold "s")

3. Start fully automatic (set "Complex" to OFF, then hold "s")

Which choices do you want? Just 1 and 3? (Fully manually or fully automatic) In that case you have 2 options:

1. Make "s" a full autostart if "Complex" is OFF

2. Remove "Complex" check box, and make "Autostart" the full automatic start. "s" then becomes always manual.

**Comment by dany93** [comment]
- I didn't know that the item "2" (Autostart) could be used with "Complex" to ON. I think this is a bit contradictory. Yes, I would remove it.

"1" (manually) and "3" (automatic) are left.
- For the choices:

I slightly prefer "1" Remove "Autostart", but that may be because I'm more used to press "s" to start. Difficult to know for most other people. 
The "2", "Autostart" option, has the advantage of a clear separation of the two modes "Auto" and "Manual".

And the "Start with engine running" option is there too.

I'm going to think more about it. Unless you or someone else have a preference.

**Comment by wlbragg** [comment]
I'm confused where this start issue is coming from. It was originally set up this way because we discussed it back then.
I think we should leave it alone.
Autostart on the first menu only is suppose to put it into a start-able state regardless of what the Aircraft options menu says. Then from that point forward your still on your own if you mess with stuff. The options in the Aircraft Options are self explanatory.
If complex is selected then even though you were in a hurry and used autostart , it is still in the complex mode.

**Comment by wkitty42** [comment]
as the token newbie, non-pilot, "i just wanna have fun" guy, i never really understood the differences... i thought there was (in order of easiest to hardest)...

1. start with engine running... OR
2. hit autostart and then 's' to start the engine... OR
3. complex - meaning do it all yourself...

i never was aware that checking or not "complex" caused autostart or 's' to do anything different than just what they stated...

personally speaking, i think the three would be the best way to go with autostart doing the setting options and 's' only spinning the engine over... 's' should not ever do anything other than turn the engine over... if priming needs to be done, tell that... otherwise, one should do everything manually (complex) or one should use autostart to do everything and then follow that by holding 's' until the engine is started... loading the sim and just hitting 's' should not start the engine... one should be told to prime and maybe even use autostart or follow the checklists for complex startup... for that matter, starting the sim and hitting 's' really shouldn't do anything if all the switches are off :wink: 

i do agree that maybe "complex" should be renamed "real" or "real life" or "full" or something similar to indicate that it means following the checklists like a real pilot does in the real world...

that's my KIS school of thought...

**Comment by dany93** [comment]
>We've turned one issue "On starter who is messing with the throttle?" into another one.
I think we should leave it alone.

No problem for me. In fact, I responded and gave my opinion because the questions arose. But the system as it was (as it is) never bothered me. Even if I didn't understand everything well.

>Think of Autostart as a one time cheat just to get your aircraft started in a hurry

Strong argument.

**Comment by onox** [comment]
> If complex is selected then even though you were in a hurry and used autostart , it is still in the complex mode.

If you have complex on and use autostart, then it's not really complex anymore, because the only remaining thing to do then is to press "s" :stuck_out_tongue_winking_eye: 

I'm slighly leaning towards option 2, it's easier for beginners and, as @dany93 said, it "has the advantage of a clear separation of the two modes "Auto" and "Manual"."

But then we should remove the "Complex" check box. I think it's vague, confusing, and unnecessary if we make "Autostart" a full autostart (initialize + cranking).

**Comment by wlbragg** [comment]
>If you have complex on and use autostart, then it's not really complex anymore, because the only remaining thing to do then is to press "s"

Yes, but the argument was that even though you used autostart and everything was set for starting. If anything gets changed it is still in complex mode and the next time you startup, everything still needs to be performed.
I don't see any reason to change anything (except possibly cranking with autostart)
Autostart was not meant to mean "non-complex", it was just to start without having to do anything (including going into another menu level and clicking on something). You are still either in complex mode or easy mode, and that depends on the menu choice.

I'm pretty sure it was gilbertohasnofb that asked for it to be this way, and at the time I didn't totally understand why, but now in practice it make total sense to me.

**Comment by wkitty42** [comment]
FWIW: i do not think that autostart should actually turn the engine over and start it... that's what "start with engine running" is for... autostart should be for seeing what happens if one follows the checklists and as a shortcut to following the checklists... nothing more... in all cases, other than "start with engine running" one should have to at least hit the 's' key to start the engine...

in fact, i think it would be a grand idea if clicking on "autostart" would bring up the checklist and walk through it, step by step, to show what is being done as it is happening... that would aid in teaching newbies how to start the craft properly... if we really want to push the realism thing...

**Comment by Juanvvc** [comment]
autostart() is defined in Nasal/engine.nas and it is a list of steps to do before cranking the engine. These steps, of course, are the same steps included in the checklists. There is not a delay or any information messages between these steps, but they could be easily introduced if it is considered interesting. I even coded an animated autoPrimer() function, but I finally decided to set a property to 3 instead of running the primer animation.

**Comment by onox** [comment]
> Autostart should do just that, start the engine and put the aircraft in a configuration to fly (your off and flying with no other steps)

Currently, "Autostart" menu item does not crank the engine.

> Expert mode should require everything including morning coffee.

In expert mode you still click "Autostart".

> "s" has always just been crank, and that is where maybe some confusion comes into play.

"s" cranks, of course, but it also executes `autostart()` if you have "Complex" turned off.

**Comment by dany93** [comment]
>Currently, "Autostart" menu item does not crank the engine.

But "Start with engine running" does (if already activated at the sim opening).
So, every possibility is available.

Whatever the choice if you change, you will find someone who would have preferred another one.
Up to some days ago, nobody complained. Which means that the current system has some value, and no important drawbacks.

**Comment by wlbragg** [comment]
>Currently, "Autostart" menu item does not crank the engine.

Right, that would be the only change I would be in favor of.

>In expert mode you still click "Autostart".

In expert mode you CAN still click "Autostart", which configures you to be flight ready even in expert mode, but does not take you out of expert mode, It just does a temporary cheat, so to speak.

>"s" cranks, of course, but it also executes autostart() if you have "Complex" turned off.

Right, and doesn't if you have "Complex" turned on. This all makes sense to me!

**Comment by onox** [comment]
In that case, lets just change the default of "Complex" to ON, so that the issue as reported by @geoffmcl is fixed.

**Comment by wlbragg** [comment]
> lets just change the default of "Complex" to ON

I guess that is OK, as long as we're sure that the users that need "simple" can negotiate the GUI

It kind of makes more sense that a user that can negotiate a complex startup procedure should be able to check or uncheck a GUI choice one time and if executing a proper exit from the sim it will remain that way. Where as a user requiring a "simple" start up procedure may also be in need of a "default" simple mode.

**Comment by wkitty42** [comment]
i still don't understand why we need four or five methods... what's wrong with the three basic ones outlined previously?

1. start with engine running... OR
2. hit autostart and then 's' to start the engine... OR
3. complex - meaning do it all yourself...
